// my-angular-form-app/src/app/form/form.component.ts
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';
import { FormService } from '../services/registration.service';
import { EmailService } from '../services/email.service';
import { validName, validEmail, validCreditCard } from '../utils/formValidation';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.css']
})
export class FormComponent {
  showErrors = false;

  constructor(
    private formService: FormService,
    private emailService: EmailService
  ) {}

  // Function to escape user input to prevent sql injection
  escapeHTML(input: string): string {
    return input.replace(/[&<>"']/g, (match) => {
      const escapeMap: { [key: string]: string } = {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#039;'
      };
      return escapeMap[match];
    });
  }

  // Validation functions
  validateName(name: string): string {
    const result = validName(name);
    return typeof result === 'string' ? result : '';
  }

  validateEmail(email: string): string {
    const result = validEmail(email);
    return typeof result === 'string' ? result : '';
  }

  validateCardNumber(cardNumber: string): string {
    const result = validCreditCard(cardNumber);
    return typeof result === 'string' ? result : '';
  }

  validateField(field: string, value: string): void {
    this.showErrors = true;
    let errorMessage = '';
    switch (field) {
      case 'name':
        errorMessage = this.validateName(value);
        break;
      case 'email':
        errorMessage = this.validateEmail(value);
        break;
      case 'cardNumber':
        errorMessage = this.validateCardNumber(value);
        break;
    }

    // Display error message if any
    const element = document.querySelector(`#${field}Error`);
    if (element) {
      element.textContent = errorMessage;
    }

    // Change the input field color based on validation result
    const inputElement = document.querySelector(`#${field}`);
    if (inputElement) {
      inputElement.classList.toggle('valid', !errorMessage);
      inputElement.classList.toggle('invalid', !!errorMessage);
    }
  }

  onSubmit(form: NgForm): void {
    this.showErrors = true;

    if (form.valid) {
      // Escape inputs before sending them to the server
      const escapedName = this.escapeHTML(form.value.name);
      const escapedEmail = this.escapeHTML(form.value.email);
      const escapedCardNumber = this.escapeHTML(form.value.cardNumber);

      const formData = new FormData();
      formData.append('name', escapedName);
      formData.append('email', escapedEmail);
      formData.append('cardNumber', escapedCardNumber);

      // Post form data to the server and send email if successful
      this.formService.postForm(formData).subscribe({
        next: (response: any) => {
          if (response.ok) {
            alert('Form submitted successfully');
            this.emailService.sendEmail(formData).subscribe();
          } else {
            alert('Form submission failed');
          }
        },
        error: (error: any) => {
          console.error('Error:', error);
          alert('Form submission failed');
        }
      });
    }
  }
}

<div class="form-container">
  <form #myForm="ngForm" (ngSubmit)="onSubmit(myForm)">
    <div class="error-messages">
      <ul>
        <li id="nameError" class="error" *ngIf="showErrors && validateName(myForm.value.name)">{{ validateName(myForm.value.name) }}</li>
        <li id="emailError" class="error" *ngIf="showErrors && validateEmail(myForm.value.email)">{{ validateEmail(myForm.value.email) }}</li>
        <li id="cardNumberError" class="error" *ngIf="showErrors && validateCardNumber(myForm.value.cardNumber)">{{ validateCardNumber(myForm.value.cardNumber) }}</li>
      </ul>
    </div>
    
    <div class="form-group">
      <label for="name">Name:</label>
      <input
        placeholder="Enter your name"
        id="name"
        name="name"
        ngModel
        (ngModelChange)="validateField('name', $event)"
        #name="ngModel"
        required
        minlength="3"
        maxlength="50"
        class="formInput"
      />
    </div>

    <div class="form-group">
      <label for="email">Email:</label>
      <input
        placeholder="Enter your email"
        id="email"
        name="email"
        ngModel
        (ngModelChange)="validateField('email', $event)"
        #email="ngModel"
        required
        email
        class="formInput"
      />
    </div>

    <div class="form-group">
      <label for="cardNumber">Card:</label>
      <input
        placeholder="Enter a Proxy Credit Card Number."
        id="cardNumber"
        name="cardNumber"
        ngModel
        (ngModelChange)="validateField('cardNumber', $event)"
        #cardNumber="ngModel"
        required
        minlength="16"
        maxlength="16"
        class="formInput"
      />
    </div>

    <button type="submit" class="submit-btn" [disabled]="myForm.invalid">Submit</button>
  </form>
</div>

// TS-FE/src/components/FormComponent.tsx
import React, { useState, useEffect } from 'react';
import { validName, validEmail, validCreditCard } from '../utils/formValidation';
import { postForm } from '../services/FormServices';
import { sendEmail } from '../services/mailgunServices';
import DOMPurify from 'dompurify'; // For sanitizing HTML content, if needed

// Function to escape user input (if needed for custom scenarios)
const escapeHTML = (str: string) => {
    return str.replace(/[&<>"']/g, (match) => {
        const escapeMap: { [key: string]: string } = {
            '&': '&amp;',
            '<': '&lt;',
            '>': '&gt;',
            '"': '&quot;',
            "'": '&#039;'
        };
        return escapeMap[match];
    });
};

const FormComponent: React.FC = () => {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [cardNumber, setCardNumber] = useState('');
    const [errors, setErrors] = useState<{ [key: string]: string }>({});

    const validateField = (value: string, validator: (value: string) => string | true, fieldName: string) => {
        const result = validator(value);
        setErrors(prevErrors => ({
            ...prevErrors,
            [fieldName]: result === true ? '' : result
        }));
    };

    

    const handleSubmit = (event: React.FormEvent) => {
        event.preventDefault();

        const nameError = validName(name);
        const emailError = validEmail(email);
        const cardError = validCreditCard(cardNumber);

        if (nameError === true && emailError === true && cardError === true) {
            // Escape user inputs before sending
            const escapedName = escapeHTML(name);
            const escapedEmail = escapeHTML(email);
            const escapedCardNumber = escapeHTML(cardNumber);

            const formData = new FormData();
            formData.append('name', escapedName);
            formData.append('email', escapedEmail);
            formData.append('cardNumber', escapedCardNumber);

            postForm(formData)
                .then(response => {
                    if (response.ok) {
                        alert('Form submitted successfully');
                        sendEmail(formData);
                    } else {
                        alert('Form submission failed');
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert('Form submission failed');
                });

           
        } else {
            setErrors({
                name: nameError === true ? '' : nameError as string,
                email: emailError === true ? '' : emailError as string,
                cardNumber: cardError === true ? '' : cardError as string
            });
        }
    };


    return (
        <>
        <div className="form-container">
        <form onSubmit={handleSubmit}>
            <div className="error-messages">
                <ul>
                    <li>{errors.name}</li>
                    <li>{errors.email}</li>
                    <li>{errors.cardNumber}</li>
                </ul>
            </div>
            <div className="form-group">
                <label htmlFor="name">Name:</label>
                <input
                    placeholder="Enter your name"
                    id="name"
                    name="name"
                    value={name}
                    onChange={(e) => {
                        setName(e.target.value);
                        validateField(e.target.value, validName, 'name');
                    }}
                    className={`formInput ${errors.name ? 'invalid' : 'valid'}`}
                />
            </div>
            <div className="form-group">
                <label htmlFor="email">Email:</label>
                <input
                    placeholder="Enter your email"
                    id="email"
                    name="email"
                    value={email}
                    onChange={(e) => {
                        setEmail(e.target.value);
                        validateField(e.target.value, validEmail, 'email');
                    }}
                    className={`formInput ${errors.email ? 'invalid' : 'valid'}`}
                />
            </div>
            <div className="form-group">
                <label htmlFor="cardNumber">Card:</label>
                <input
                    placeholder="Enter a Proxy Credit Card Number."
                    id="cardNumber"
                    name="cardNumber"
                    value={cardNumber}
                    onChange={(e) => {
                        setCardNumber(e.target.value);
                        validateField(e.target.value, validCreditCard, 'cardNumber');
                    }}
                    className={`formInput ${errors.cardNumber ? 'invalid' : 'valid'}`}
                />
            </div>
            <button type="submit" className="submit-btn">Submit</button>
        </form>
        </div>
        </>
    );
};

export default FormComponent;
